# Generated by Django 5.2.5 on 2025-08-20 00:04

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='published_date',
            field=models.DateField(auto_now_add=True, default=datetime.date(2025, 8, 19), verbose_name='Data de Publicação'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Conteúdo'),
        ),
    ]
